version: "3"

services:
  jazmeendeco_mysql:
    image: mysql:5.7
    container_name: jazmeendeco_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mil998
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=mil998
      - MYSQL_DATABASE=jazmeendeco
    ports: 
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  jazmeendeco_mongo:
    image: mongo:latest
    container_name: jazmeendeco_mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  # migration:
  #   build: .
  #   command: node ./scripts/mongo/seed-admin.js
